#pragma once
#include "vars.hpp"
#include <string>
#include <algorithm>
class PaintKit {
public:
    ItemDefinitionIndex weapon_type;
    std::string skin_name;
    int paintkit_id;

    PaintKit(int w_type, std::string s_name, int pkit_id)
        : weapon_type(static_cast<ItemDefinitionIndex>(w_type)), skin_name(s_name), paintkit_id(pkit_id) {
    }
    PaintKit() : weapon_type(ItemDefinitionIndex(0)), skin_name(""), paintkit_id(0) {}
};

std::vector<PaintKit> paintkits = {
    PaintKit(1, "hy_ddpat_urb", 17),
    PaintKit(1, "aa_flames", 37),
    PaintKit(1, "aa_vertigo", 61),
    PaintKit(1, "hy_mottled_sand", 90),
    PaintKit(1, "am_scales_bravo", 185),
    PaintKit(1, "am_ddpatdense_peacock", 231),
    PaintKit(1, "hy_webs_darker", 232),
    PaintKit(1, "hy_varicamo_urban", 237),
    PaintKit(1, "aq_engraved_deagle", 273),
    PaintKit(1, "am_crystallized_dark", 296),
    PaintKit(1, "aq_handcannon", 328),
    PaintKit(1, "aq_pilot_deagle", 347),
    PaintKit(1, "cu_deagle_aureus", 351),
    PaintKit(2, "an_navy", 28),
    PaintKit(2, "aq_forced", 43),
    PaintKit(2, "so_pmc", 46),
    PaintKit(2, "so_space_marine", 47),
    PaintKit(2, "so_tangerine", 153),
    PaintKit(2, "cu_season_elites_bravo", 190),
    PaintKit(2, "am_ossify_red", 220),
    PaintKit(2, "am_crystallized_blue", 249),
    PaintKit(2, "hy_marina_sunrise", 261),
    PaintKit(2, "so_panther", 276),
    PaintKit(2, "cu_retribution", 307),
    PaintKit(2, "hy_vines", 330),
    PaintKit(3, "so_red", 3),
    PaintKit(3, "aq_oiled", 44),
    PaintKit(3, "so_pmc", 46),
    PaintKit(3, "hy_forest_night", 78),
    PaintKit(3, "sp_tape_orange", 141),
    PaintKit(3, "so_jungle", 151),
    PaintKit(3, "an_gunmetal_bravo", 210),
    PaintKit(3, "hy_flowers", 223),
    PaintKit(3, "am_crystallized_silver", 252),
    PaintKit(3, "hy_kami", 265),
    PaintKit(3, "am_copper_flecks", 274),
    PaintKit(3, "aq_57_feathers", 352),
    PaintKit(3, "so_grey_nuclear_orange_five_seven", 377),
    PaintKit(3, "cu_fiveseven_urban_hazard", 387),
    PaintKit(4, "so_olive", 2),
    PaintKit(4, "so_red", 3),
    PaintKit(4, "aa_fade", 38),
    PaintKit(4, "so_night", 40),
    PaintKit(4, "am_dragon_glock", 48),
    PaintKit(4, "aq_brass", 159),
    PaintKit(4, "so_sand_bravo", 208),
    PaintKit(4, "am_ddpatdense_silver", 230),
    PaintKit(4, "hy_craquelure", 278),
    PaintKit(4, "hy_nerodia", 293),
    PaintKit(4, "cu_glock-liquescent", 353),
    PaintKit(4, "am_nuclear_pattern1_glock", 367),
    PaintKit(4, "aq_glock_coiled", 381),
    PaintKit(7, "hy_ak47lam", 14),
    PaintKit(7, "aq_oiled", 44),
    PaintKit(7, "sp_mesh_tan", 72),
    PaintKit(7, "sp_spray_jungle", 122),
    PaintKit(7, "sp_zebracam", 170),
    PaintKit(7, "hy_ak47lam_bw", 172),
    PaintKit(7, "cu_fireserpent_ak47_bravo", 180),
    PaintKit(7, "hy_ak47lam_blue", 226),
    PaintKit(7, "cu_ak47_cobra", 282),
    PaintKit(7, "cu_pinstripe_ak47", 300),
    PaintKit(7, "cu_ak47_rubber", 302),
    PaintKit(7, "cu_panther_ak47", 316),
    PaintKit(7, "cu_well_traveled_ak47", 340),
    PaintKit(7, "cu_green_leather_ak47", 341),
    PaintKit(7, "cu_tribute_ak47", 380),
    PaintKit(8, "hy_tiger", 9),
    PaintKit(8, "hy_copperhead", 10),
    PaintKit(8, "an_red", 33),
    PaintKit(8, "so_pmc", 46),
    PaintKit(8, "so_space_marine", 47),
    PaintKit(8, "hy_feathers_aug", 73),
    PaintKit(8, "so_stormfront", 100),
    PaintKit(8, "sp_mesh_forest_fire", 110),
    PaintKit(8, "an_navy_bravo", 197),
    PaintKit(8, "cu_aug_chameleonaire", 280),
    PaintKit(8, "cu_aug_progressiv", 305),
    PaintKit(8, "sp_nukestripe_orange_aug", 375),
    PaintKit(9, "sp_snake", 30),
    PaintKit(9, "am_lightning_awp", 51),
    PaintKit(9, "sp_mesh_tan", 72),
    PaintKit(9, "hy_ddpat_pink", 84),
    PaintKit(9, "hy_blam_simple", 174),
    PaintKit(9, "cu_favela_awp", 181),
    PaintKit(9, "am_crumple_bravo", 212),
    PaintKit(9, "hy_hive", 227),
    PaintKit(9, "hy_snakeskin", 251),
    PaintKit(9, "cu_awp_cobra", 259),
    PaintKit(9, "cu_awp_asimov", 279),
    PaintKit(9, "cu_medieval_dragon_awp", 344),
    PaintKit(10, "sp_spray", 22),
    PaintKit(10, "so_space_marine", 47),
    PaintKit(10, "hy_reef", 92),
    PaintKit(10, "cu_broken_path_famas", 154),
    PaintKit(10, "hy_doomkitty", 178),
    PaintKit(10, "sp_spitfire_famas_bravo", 194),
    PaintKit(10, "hy_bluehex", 218),
    PaintKit(10, "sp_mesh_hot_and_cold", 244),
    PaintKit(10, "cu_famas_pulse", 260),
    PaintKit(10, "an_famas_sgt", 288),
    PaintKit(10, "am_nuclear_skulls2_famas", 371),
    PaintKit(11, "hy_arctic", 6),
    PaintKit(11, "hy_desert", 8),
    PaintKit(11, "so_pmc", 46),
    PaintKit(11, "sp_mesh_tan", 72),
    PaintKit(11, "hy_arctic_contrast", 74),
    PaintKit(11, "sp_tape_short_jungle", 147),
    PaintKit(11, "hy_bluepolygon_bravo", 195),
    PaintKit(11, "sp_zebracam_blue", 229),
    PaintKit(11, "hy_varicamo", 235),
    PaintKit(11, "so_green", 294),
    PaintKit(11, "am_g3sg1_murky", 382),
    PaintKit(13, "hy_forest_winter", 76),
    PaintKit(13, "hy_ddpat_orange", 83),
    PaintKit(13, "sp_spray_desert_sage", 119),
    PaintKit(13, "hy_crumple_bravo", 192),
    PaintKit(13, "an_titanium30v", 216),
    PaintKit(13, "hy_varicamo", 235),
    PaintKit(13, "sp_mesh_slashes", 241),
    PaintKit(13, "cu_sandstorm", 264),
    PaintKit(13, "so_orca", 297),
    PaintKit(13, "hy_galil_kami", 308),
    PaintKit(13, "cu_cerbrus_galil", 379),
    PaintKit(14, "sp_spray", 22),
    PaintKit(14, "hy_blizzard", 75),
    PaintKit(14, "hy_ddpat_jungle_bravo", 202),
    PaintKit(14, "sp_mesh_python", 243),
    PaintKit(14, "aq_obsidian", 266),
    PaintKit(16, "hy_desert", 8),
    PaintKit(16, "hy_v_tiger", 16),
    PaintKit(16, "hy_ddpat_urb", 17),
    PaintKit(16, "so_tornado", 101),
    PaintKit(16, "cu_bullet_rain_m4a1", 155),
    PaintKit(16, "hy_hunter_modern", 164),
    PaintKit(16, "sp_nukestripe_orange", 167),
    PaintKit(16, "sp_zebracam_bw", 176),
    PaintKit(16, "sp_star_bravo", 187),
    PaintKit(16, "cu_xray_m4", 215),
    PaintKit(16, "cu_m4_asimov", 255),
    PaintKit(16, "cu_m4a1_howling", 309),
    PaintKit(16, "cu_titanstorm", 336),
    PaintKit(16, "cu_m4a4_griffin", 384),
    PaintKit(17, "so_red", 3),
    PaintKit(17, "hy_ddpat_urb", 17),
    PaintKit(17, "an_silver", 32),
    PaintKit(17, "so_purple", 98),
    PaintKit(17, "so_tornado", 101),
    PaintKit(17, "sp_palm", 157),
    PaintKit(17, "aq_etched_mac10_bravo", 188),
    PaintKit(17, "aa_fade_metallic", 246),
    PaintKit(17, "cu_mac10_redhot", 284),
    PaintKit(17, "cu_mac10_decay", 310),
    PaintKit(17, "so_indigo_and_grey", 333),
    PaintKit(17, "cu_korupt", 337),
    PaintKit(17, "cu_luggage_mac10", 343),
    PaintKit(17, "am_nuclear_skulls3_mac10", 372),
    PaintKit(19, "hy_zombie", 20),
    PaintKit(19, "am_slither_p90", 67),
    PaintKit(19, "so_stormfront", 100),
    PaintKit(19, "sp_mesh_glacier", 111),
    PaintKit(19, "sp_spray_sand", 124),
    PaintKit(19, "cu_catskulls_p90", 156),
    PaintKit(19, "sp_nukestripe_maroon", 169),
    PaintKit(19, "sp_dapple", 175),
    PaintKit(19, "cu_dragon_p90_bravo", 182),
    PaintKit(19, "hy_modspots", 228),
    PaintKit(19, "sp_twigs", 234),
    PaintKit(19, "sp_mesh_hot_and_cold", 244),
    PaintKit(19, "cu_p90_trigon", 283),
    PaintKit(19, "cu_p90_scorpius", 311),
    PaintKit(19, "an_royalbleed", 335),
    PaintKit(19, "cu_brown_leather_p90", 342),
    PaintKit(19, "cu_p90-asiimov", 359),
    PaintKit(24, "hy_gelpen", 15),
    PaintKit(24, "hy_ddpat_urb", 17),
    PaintKit(24, "aa_flames", 37),
    PaintKit(24, "am_carbon_fiber", 70),
    PaintKit(24, "so_caramel", 93),
    PaintKit(24, "sp_nukestripe_maroon", 169),
    PaintKit(24, "sp_dapple", 175),
    PaintKit(24, "sp_skull_diagram_bravo", 193),
    PaintKit(24, "cu_ump_corporal", 281),
    PaintKit(24, "so_indigo_and_grey", 333),
    PaintKit(24, "hy_lines_orange", 362),
    PaintKit(24, "sp_ump45_d-visions", 392),
    PaintKit(25, "aq_blued", 42),
    PaintKit(25, "so_grassland", 95),
    PaintKit(25, "so_moss", 96),
    PaintKit(25, "sp_tape_dots_urban", 135),
    PaintKit(25, "hy_hunter_blaze_orange", 166),
    PaintKit(25, "sp_nukestripe_maroon", 169),
    PaintKit(25, "so_jungle_bravo", 205),
    PaintKit(25, "hy_varicamo_blue", 238),
    PaintKit(25, "hy_varicamo_desert", 240),
    PaintKit(25, "cu_xm1014_heaven_guard", 314),
    PaintKit(25, "hy_snakeskin_red", 320),
    PaintKit(25, "cu_leather_xm1014", 348),
    PaintKit(25, "am_nuclear_skulls1_xm1014", 370),
    PaintKit(25, "cu_xm1014_caritas", 393),
    PaintKit(26, "hy_splatter", 13),
    PaintKit(26, "sp_leaves", 25),
    PaintKit(26, "am_carbon_fiber", 70),
    PaintKit(26, "sp_tape_short_sand", 148),
    PaintKit(26, "sp_tape_short_urban", 149),
    PaintKit(26, "aq_brass", 159),
    PaintKit(26, "hy_hunter_modern", 164),
    PaintKit(26, "sp_nukestripe_brown", 171),
    PaintKit(26, "aq_steel_bravo", 203),
    PaintKit(26, "hy_water_crest", 224),
    PaintKit(26, "hy_varicamo_night", 236),
    PaintKit(26, "am_turqoise_halftone", 267),
    PaintKit(26, "cu_bizon_antique", 306),
    PaintKit(26, "cu_bizon-osiris", 349),
    PaintKit(26, "so_grey_nuclear_green_bizon", 376),
    PaintKit(27, "an_silver", 32),
    PaintKit(27, "am_urban", 34),
    PaintKit(27, "so_yellow", 39),
    PaintKit(27, "so_sand", 99),
    PaintKit(27, "so_stormfront", 100),
    PaintKit(27, "sp_nukestripe_brown", 171),
    PaintKit(27, "hy_icosahedron", 177),
    PaintKit(27, "sp_hazard_bravo", 198),
    PaintKit(27, "cu_mag7_heaven", 291),
    PaintKit(27, "sp_mag7_firebitten", 385),
    PaintKit(28, "an_navy", 28),
    PaintKit(28, "sp_palm_bravo", 201),
    PaintKit(28, "hy_varicamo_desert", 240),
    PaintKit(28, "sp_negev_turq_terrain", 285),
    PaintKit(28, "am_army_shine", 298),
    PaintKit(28, "cu_bratatat_negev", 317),
    PaintKit(28, "cu_negev_titanstorm", 355),
    PaintKit(28, "sp_nuclear_pattern3_negev", 369),
    PaintKit(29, "hy_ddpat", 5),
    PaintKit(29, "sp_snake", 30),
    PaintKit(29, "aq_copper", 41),
    PaintKit(29, "hy_ddpat_orange", 83),
    PaintKit(29, "sp_spray_desert_sage", 119),
    PaintKit(29, "sp_nukestripe_brown", 171),
    PaintKit(29, "hy_ali_tile_bravo", 204),
    PaintKit(29, "aa_fade_metallic", 246),
    PaintKit(29, "hy_varicamo_red", 250),
    PaintKit(29, "cu_sawedoff_octopump", 256),
    PaintKit(29, "aq_steel", 323),
    PaintKit(29, "cu_green_leather_sawedoff", 345),
    PaintKit(29, "aq_sawedoff_blackgold", 390),
    PaintKit(30, "so_olive", 2),
    PaintKit(30, "hy_ddpat_urb", 17),
    PaintKit(30, "am_ossify", 36),
    PaintKit(30, "aq_brass", 159),
    PaintKit(30, "sp_nukestripe_green_tec9", 179),
    PaintKit(30, "so_tornado_bravo", 206),
    PaintKit(30, "an_titanium30v", 216),
    PaintKit(30, "hy_varicamo", 235),
    PaintKit(30, "sp_mesh_army", 242),
    PaintKit(30, "am_crystallized", 248),
    PaintKit(30, "am_fluted_tec9", 272),
    PaintKit(30, "cu_tec9_sandstorm", 289),
    PaintKit(30, "cu_tec9_asiimov", 303),
    PaintKit(30, "hy_nuclear_skulls5_tec9", 374),
    PaintKit(32, "hy_granite", 21),
    PaintKit(32, "an_silver", 32),
    PaintKit(32, "am_scorpion_p2000", 71),
    PaintKit(32, "so_grassland", 95),
    PaintKit(32, "sp_leaves_grassland", 104),
    PaintKit(32, "cu_favela_p2000", 184),
    PaintKit(32, "am_ossify_blue_p2000_bravo", 211),
    PaintKit(32, "aa_fade_metallic", 246),
    PaintKit(32, "hy_poly_camo", 275),
    PaintKit(32, "am_chainmail", 327),
    PaintKit(32, "cu_p2000_pulse", 338),
    PaintKit(32, "cu_luggage_p2000", 346),
    PaintKit(32, "cu_p2000_ivory", 357),
    PaintKit(32, "cu_p2000_fire_elemental", 389),
    PaintKit(33, "hy_ddpat", 5),
    PaintKit(33, "hy_skulls", 11),
    PaintKit(33, "hy_gelpen", 15),
    PaintKit(33, "an_navy", 28),
    PaintKit(33, "so_whiteout", 102),
    PaintKit(33, "sp_tape_orange", 141),
    PaintKit(33, "so_olive_bravo", 209),
    PaintKit(33, "am_ossify_blue", 213),
    PaintKit(33, "sp_spray_army", 245),
    PaintKit(33, "cu_mp7-commander", 354),
    PaintKit(33, "hy_plaid1", 365),
    PaintKit(34, "an_red", 33),
    PaintKit(34, "so_yellow", 39),
    PaintKit(34, "aa_vertigo", 61),
    PaintKit(34, "so_stormfront", 100),
    PaintKit(34, "sp_tape_orange", 141),
    PaintKit(34, "sp_tape_short_sand", 148),
    PaintKit(34, "sp_tape_dots_bravo", 199),
    PaintKit(34, "am_thorny_rose_mp9", 262),
    PaintKit(34, "am_metal_inlay", 329),
    PaintKit(34, "hy_plaid2", 366),
    PaintKit(34, "hy_nuclear_pattern2_mp9", 368),
    PaintKit(34, "cu_mp9_chevron", 386),
    PaintKit(35, "so_red", 3),
    PaintKit(35, "sp_leaves", 25),
    PaintKit(35, "cu_spring_nova", 62),
    PaintKit(35, "so_sand", 99),
    PaintKit(35, "sp_mesh_arctic_contrast", 107),
    PaintKit(35, "cu_walnut_nova", 158),
    PaintKit(35, "hy_hunter_modern", 164),
    PaintKit(35, "hy_hunter_blaze_orange", 166),
    PaintKit(35, "sp_zebracam", 170),
    PaintKit(35, "hy_seaside_bravo", 191),
    PaintKit(35, "am_crumple", 214),
    PaintKit(35, "sp_camo_wood_blue", 225),
    PaintKit(35, "cu_skull_nova", 263),
    PaintKit(35, "cu_nova_antique", 286),
    PaintKit(35, "so_green", 294),
    PaintKit(35, "am_oval_hex", 299),
    PaintKit(35, "cu_nova_koi", 356),
    PaintKit(36, "hy_gelpen", 15),
    PaintKit(36, "sp_tape", 27),
    PaintKit(36, "am_urban", 34),
    PaintKit(36, "hy_forest_boreal", 77),
    PaintKit(36, "so_sand", 99),
    PaintKit(36, "sp_splash_p250", 162),
    PaintKit(36, "hy_hunter_modern", 164),
    PaintKit(36, "sp_nukestripe_green", 168),
    PaintKit(36, "hy_crumple_dark_bravo", 207),
    PaintKit(36, "hy_redhex", 219),
    PaintKit(36, "am_ddpatdense_silver", 230),
    PaintKit(36, "cu_p250_refined", 258),
    PaintKit(36, "am_p250_beaded_paint", 271),
    PaintKit(36, "cu_money", 295),
    PaintKit(36, "cu_bittersweet", 358),
    PaintKit(36, "hy_nuclear_skulls4_p250", 373),
    PaintKit(36, "aq_p250_cartel", 388),
    PaintKit(38, "so_pmc", 46),
    PaintKit(38, "am_carbon_fiber", 70),
    PaintKit(38, "so_stormfront", 100),
    PaintKit(38, "sp_mesh_sand", 116),
    PaintKit(38, "sp_palm", 157),
    PaintKit(38, "hy_hunter_blaze_pink", 165),
    PaintKit(38, "an_emerald_bravo", 196),
    PaintKit(38, "hy_webs_darker", 232),
    PaintKit(38, "cu_scar_cyrex", 312),
    PaintKit(38, "cu_scar20_intervention", 391),
    PaintKit(39, "an_navy", 28),
    PaintKit(39, "so_purple", 98),
    PaintKit(39, "so_tornado", 101),
    PaintKit(39, "sp_tape_dots_waves", 136),
    PaintKit(39, "sp_spray_waves_bravo", 186),
    PaintKit(39, "sp_mesh_python", 243),
    PaintKit(39, "aq_damascus_sg553", 247),
    PaintKit(39, "cu_sg553_pulse", 287),
    PaintKit(39, "am_army_shine", 298),
    PaintKit(39, "cu_luggage_sg553", 363),
    PaintKit(39, "sp_nukestripe_maroon_sg553", 378),
    PaintKit(40, "sp_short_tape", 26),
    PaintKit(40, "am_zebra_dark", 60),
    PaintKit(40, "so_moss", 96),
    PaintKit(40, "so_sand", 99),
    PaintKit(40, "hy_mayan_dreams_bravo", 200),
    PaintKit(40, "cu_shark", 222),
    PaintKit(40, "sp_palm_shadow", 233),
    PaintKit(40, "aa_fade_grassland", 253),
    PaintKit(40, "cu_ssg08_immortal", 304),
    PaintKit(40, "hy_ssg08_marker", 319),
    PaintKit(40, "aq_leviathan", 361),
    PaintKit(60, "am_zebra_dark", 60),
    PaintKit(60, "hy_forest_boreal", 77),
    PaintKit(60, "hy_ocean_bravo", 189),
    PaintKit(60, "hy_redtiger", 217),
    PaintKit(60, "hy_varicamo", 235),
    PaintKit(60, "so_orange_accents", 254),
    PaintKit(60, "cu_m4a1-s_elegant", 257),
    PaintKit(60, "am_m4a1-s_alloy_orange", 301),
    PaintKit(60, "cu_m4a1-s_silence", 321),
    PaintKit(60, "am_metals", 326),
    PaintKit(60, "cu_m4a1s_cyrex", 360),
    PaintKit(60, "aq_m4a1s_basilisk", 383),
    PaintKit(61, "sp_leaves", 25),
    PaintKit(61, "am_zebra_dark", 60),
    PaintKit(61, "hy_siege_bravo", 183),
    PaintKit(61, "hy_redtiger", 217),
    PaintKit(61, "am_electric_red", 221),
    PaintKit(61, "hy_varicamo_night", 236),
    PaintKit(61, "aq_usp_stainless", 277),
    PaintKit(61, "cu_usp_elegant", 290),
    PaintKit(61, "cu_usp_spitfire", 313),
    PaintKit(61, "cu_usp_sandpapered", 318),
    PaintKit(61, "hy_indigo_usp", 332),
    PaintKit(61, "cu_kaiman", 339),
    PaintKit(61, "cu_luggage_usp-s", 364),
    PaintKit(63, "hy_webs", 12),
    PaintKit(63, "hy_bluehex", 218),
    PaintKit(63, "am_diamond_plate", 268),
    PaintKit(63, "am_fuschia", 269),
    PaintKit(63, "aq_etched_cz75", 270),
    PaintKit(63, "so_orca", 297),
    PaintKit(63, "am_nitrogen", 315),
    PaintKit(63, "so_orange_accents2", 322),
    PaintKit(63, "am_royal", 325),
    PaintKit(63, "am_gyrate", 334),
    PaintKit(63, "cu_c75a-tiger", 350),
    PaintKit(63, "hy_plaid2", 366),
    PaintKit(500, "hy_ddpat", 5),
    PaintKit(500, "hy_webs", 12),
    PaintKit(500, "aa_fade", 38),
    PaintKit(500, "so_night", 40),
    PaintKit(500, "aq_blued", 42),
    PaintKit(500, "aq_forced", 43),
    PaintKit(500, "aq_oiled", 44),
    PaintKit(500, "am_zebra", 59),
    PaintKit(500, "sp_mesh_tan", 72),
    PaintKit(500, "hy_forest_boreal", 77),
    PaintKit(500, "sp_tape_urban", 143),
    PaintKit(500, "sp_dapple", 175),
    PaintKit(505, "hy_ddpat", 5),
    PaintKit(505, "hy_webs", 12),
    PaintKit(505, "aa_fade", 38),
    PaintKit(505, "so_night", 40),
    PaintKit(505, "aq_blued", 42),
    PaintKit(505, "aq_forced", 43),
    PaintKit(505, "aq_oiled", 44),
    PaintKit(505, "am_zebra", 59),
    PaintKit(505, "sp_mesh_tan", 72),
    PaintKit(505, "hy_forest_boreal", 77),
    PaintKit(505, "sp_tape_urban", 143),
    PaintKit(505, "sp_dapple", 175),
    PaintKit(506, "hy_ddpat", 5),
    PaintKit(506, "hy_webs", 12),
    PaintKit(506, "aa_fade", 38),
    PaintKit(506, "so_night", 40),
    PaintKit(506, "aq_blued", 42),
    PaintKit(506, "aq_forced", 43),
    PaintKit(506, "aq_oiled", 44),
    PaintKit(506, "am_zebra", 59),
    PaintKit(506, "sp_mesh_tan", 72),
    PaintKit(506, "hy_forest_boreal", 77),
    PaintKit(506, "sp_tape_urban", 143),
    PaintKit(506, "sp_dapple", 175),
    PaintKit(507, "hy_ddpat", 5),
    PaintKit(507, "hy_webs", 12),
    PaintKit(507, "aa_fade", 38),
    PaintKit(507, "so_night", 40),
    PaintKit(507, "aq_blued", 42),
    PaintKit(507, "aq_forced", 43),
    PaintKit(507, "aq_oiled", 44),
    PaintKit(507, "am_zebra", 59),
    PaintKit(507, "sp_mesh_tan", 72),
    PaintKit(507, "hy_forest_boreal", 77),
    PaintKit(507, "sp_tape_urban", 143),
    PaintKit(507, "sp_dapple", 175),
    PaintKit(508, "hy_ddpat", 5),
    PaintKit(508, "hy_webs", 12),
    PaintKit(508, "aa_fade", 38),
    PaintKit(508, "so_night", 40),
    PaintKit(508, "aq_blued", 42),
    PaintKit(508, "aq_forced", 43),
    PaintKit(508, "aq_oiled", 44),
    PaintKit(508, "am_zebra", 59),
    PaintKit(508, "sp_mesh_tan", 72),
    PaintKit(508, "hy_forest_boreal", 77),
    PaintKit(508, "sp_tape_urban", 143),
    PaintKit(508, "sp_dapple", 175),
    PaintKit(509, "hy_ddpat", 5),
    PaintKit(509, "hy_webs", 12),
    PaintKit(509, "aa_fade", 38),
    PaintKit(509, "so_night", 40),
    PaintKit(509, "aq_blued", 42),
    PaintKit(509, "aq_forced", 43),
    PaintKit(509, "aq_oiled", 44),
    PaintKit(509, "am_zebra", 59),
    PaintKit(509, "sp_mesh_tan", 72),
    PaintKit(509, "hy_forest_boreal", 77),
    PaintKit(509, "sp_tape_urban", 143),
    PaintKit(509, "sp_dapple", 175),
    PaintKit(515, "hy_ddpat", 5),
    PaintKit(515, "hy_webs", 12),
    PaintKit(515, "aa_fade", 38),
    PaintKit(515, "so_night", 40),
    PaintKit(515, "aq_blued", 42),
    PaintKit(515, "aq_forced", 43),
    PaintKit(515, "aq_oiled", 44),
    PaintKit(515, "am_zebra", 59),
    PaintKit(515, "sp_mesh_tan", 72),
    PaintKit(515, "hy_forest_boreal", 77),
    PaintKit(515, "sp_tape_urban", 143),
    PaintKit(515, "sp_dapple", 175),
};
std::unordered_map<std::string, std::string> paintkitnames = {
        {"so_olive", "Groundwater"},
        {"so_red", "Candy Apple"},
        {"hy_ddpat", "Forest DDPAT"},
        {"hy_arctic", "Arctic Camo"},
        {"hy_desert", "Desert Storm"},
        {"hy_tiger", "Bengal Tiger"},
        {"hy_copperhead", "Copperhead"},
        {"hy_skulls", "Skulls"},
        {"hy_webs", "Crimson Web"},
        {"hy_splatter", "Blue Streak"},
        {"hy_ak47lam", "Red Laminate"},
        {"hy_gelpen", "Gunsmoke"},
        {"hy_v_tiger", "Jungle Tiger"},
        {"hy_ddpat_urb", "Urban DDPAT"},
        {"hy_zombie", "Virus"},
        {"hy_granite", "Granite Marbleized"},
        {"sp_spray", "Contrast Spray"},
        {"sp_leaves", "Forest Leaves"},
        {"sp_short_tape", "Lichen Dashed"},
        {"sp_tape", "Bone Mask"},
        {"an_navy", "Anodized Navy"},
        {"sp_snake", "Snake Camo"},
        {"an_silver", "Silver"},
        {"an_red", "Hot Rod"},
        {"am_urban", "Metallic DDPAT"},
        {"am_ossify", "Ossified"},
        {"aa_flames", "Blaze"},
        {"aa_fade", "Fade"},
        {"so_yellow", "Bulldozer"},
        {"so_night", "Night"},
        {"aq_copper", "Copper"},
        {"aq_blued", "Blue Steel"},
        {"aq_forced", "Stained"},
        {"aq_oiled", "Case Hardened"},
        {"so_pmc", "Contractor"},
        {"so_space_marine", "Colony"},
        {"am_dragon_glock", "Dragon Tattoo"},
        {"am_lightning_awp", "Lightning Strike"},
        {"am_zebra", "Slaughter"},
        {"am_zebra_dark", "Dark Water"},
        {"aa_vertigo", "Hypnotic"},
        {"cu_spring_nova", "Bloomstick"},
        {"am_slither_p90", "Cold Blooded"},
        {"am_carbon_fiber", "Carbon Fiber"},
        {"am_scorpion_p2000", "Scorpion"},
        {"sp_mesh_tan", "Safari Mesh"},
        {"hy_feathers_aug", "Wings"},
        {"hy_arctic_contrast", "Polar Camo"},
        {"hy_blizzard", "Blizzard Marbleized"},
        {"hy_forest_winter", "Winter Forest"},
        {"hy_forest_boreal", "Boreal Forest"},
        {"hy_forest_night", "Forest Night"},
        {"hy_ddpat_orange", "Orange DDPAT"},
        {"hy_ddpat_pink", "Pink DDPAT"},
        {"hy_mottled_sand", "Mudder"},
        {"hy_reef", "Cyanospatter"},
        {"so_caramel", "Caramel"},
        {"so_grassland", "Grassland"},
        {"so_moss", "Blue Spruce"},
        {"so_purple", "Ultraviolet"},
        {"so_sand", "Sand Dune"},
        {"so_stormfront", "Storm"},
        {"so_tornado", "Tornado"},
        {"so_whiteout", "Whiteout"},
        {"sp_leaves_grassland", "Grassland Leaves"},
        {"sp_mesh_arctic_contrast", "Polar Mesh"},
        {"sp_mesh_forest_fire", "Condemned"},
        {"sp_mesh_glacier", "Glacier Mesh"},
        {"sp_mesh_sand", "Sand Mesh"},
        {"sp_spray_desert_sage", "Sage Spray"},
        {"sp_spray_jungle", "Jungle Spray"},
        {"sp_spray_sand", "Sand Spray"},
        {"sp_tape_dots_urban", "Urban Perforated"},
        {"sp_tape_dots_waves", "Waves Perforated"},
        {"sp_tape_orange", "Orange Peel"},
        {"sp_tape_urban", "Urban Masked"},
        {"sp_tape_short_jungle", "Jungle Dashed"},
        {"sp_tape_short_sand", "Sand Dashed"},
        {"sp_tape_short_urban", "Urban Dashed"},
        {"so_jungle", "Jungle"},
        {"so_tangerine", "Demolition"},
        {"cu_broken_path_famas", "Afterimage"},
        {"cu_bullet_rain_m4a1", "Bullet Rain"},
        {"cu_catskulls_p90", "Death by Kitty"},
        {"sp_palm", "Palm"},
        {"cu_walnut_nova", "Walnut"},
        {"aq_brass", "Brass"},
        {"sp_splash_p250", "Splash"},
        {"hy_hunter_modern", "Modern Hunter"},
        {"hy_hunter_blaze_pink", "Splash Jam"},
        {"hy_hunter_blaze_orange", "Blaze Orange"},
        {"sp_nukestripe_orange", "Radiation Hazard"},
        {"sp_nukestripe_green", "Nuclear Threat"},
        {"sp_nukestripe_maroon", "Fallout Warning"},
        {"sp_zebracam", "Predator"},
        {"sp_nukestripe_brown", "Irradiated Alert"},
        {"hy_ak47lam_bw", "Black Laminate"},
        {"hy_blam_simple", "BOOM"},
        {"sp_dapple", "Scorched"},
        {"sp_zebracam_bw", "Faded Zebra"},
        {"hy_icosahedron", "Memento"},
        {"hy_doomkitty", "Doomkitty"},
        {"sp_nukestripe_green_tec9", "Nuclear Threat"},
        {"cu_fireserpent_ak47_bravo", "Fire Serpent"},
        {"cu_favela_awp", "Corticera"},
        {"cu_dragon_p90_bravo", "Emerald Dragon"},
        {"hy_siege_bravo", "Overgrowth"},
        {"cu_favela_p2000", "Corticera"},
        {"am_scales_bravo", "Golden Koi"},
        {"sp_spray_waves_bravo", "Wave Spray"},
        {"sp_star_bravo", "Zirka"},
        {"aq_etched_mac10_bravo", "Graven"},
        {"hy_ocean_bravo", "Bright Water"},
        {"cu_season_elites_bravo", "Black Limba"},
        {"hy_seaside_bravo", "Tempest"},
        {"hy_crumple_bravo", "Shattered"},
        {"sp_skull_diagram_bravo", "Bone Pile"},
        {"sp_spitfire_famas_bravo", "Spitfire"},
        {"hy_bluepolygon_bravo", "Demeter"},
        {"an_emerald_bravo", "Emerald"},
        {"an_navy_bravo", "Anodized Navy"},
        {"sp_hazard_bravo", "Hazard"},
        {"sp_tape_dots_bravo", "Dry Season"},
        {"hy_mayan_dreams_bravo", "Mayan Dreams"},
        {"sp_palm_bravo", "Palm"},
        {"hy_ddpat_jungle_bravo", "Jungle DDPAT"},
        {"aq_steel_bravo", "Rust Coat"},
        {"hy_ali_tile_bravo", "Mosaico"},
        {"so_jungle_bravo", "Jungle"},
        {"so_tornado_bravo", "Tornado"},
        {"hy_crumple_dark_bravo", "Facets"},
        {"so_sand_bravo", "Sand Dune"},
        {"so_olive_bravo", "Groundwater"},
        {"an_gunmetal_bravo", "Anodized Gunmetal"},
        {"am_ossify_blue_p2000_bravo", "Ocean Foam"},
        {"am_crumple_bravo", "Graphite"},
        {"am_ossify_blue", "Ocean Foam"},
        {"am_crumple", "Graphite"},
        {"cu_xray_m4", "X-Ray"},
        {"an_titanium30v", "Blue Titanium"},
        {"hy_redtiger", "Blood Tiger"},
        {"hy_bluehex", "Hexane"},
        {"hy_redhex", "Hive"},
        {"am_ossify_red", "Hemoglobin"},
        {"am_electric_red", "Serum"},
        {"cu_shark", "Blood in the Water"},
        {"hy_flowers", "Nightshade"},
        {"hy_water_crest", "Water Sigil"},
        {"sp_camo_wood_blue", "Ghost Camo"},
        {"hy_ak47lam_blue", "Blue Laminate"},
        {"hy_hive", "Electric Hive"},
        {"hy_modspots", "Blind Spot"},
        {"sp_zebracam_blue", "Azure Zebra"},
        {"am_ddpatdense_silver", "Steel Disruption"},
        {"am_ddpatdense_peacock", "Cobalt Disruption"},
        {"hy_webs_darker", "Crimson Web"},
        {"sp_palm_shadow", "Tropical Storm"},
        {"sp_twigs", "Ash Wood"},
        {"hy_varicamo", "VariCamo"},
        {"hy_varicamo_night", "Night Ops"},
        {"hy_varicamo_urban", "Urban Rubble"},
        {"hy_varicamo_blue", "VariCamo Blue"},
        {"hy_varicamo_desert", "CaliCamo"},
        {"sp_mesh_slashes", "Hunting Blind"},
        {"sp_mesh_army", "Army Mesh"},
        {"sp_mesh_python", "Gator Mesh"},
        {"sp_mesh_hot_and_cold", "Teardown"},
        {"sp_spray_army", "Army Recon"},
        {"aa_fade_metallic", "Amber Fade"},
        {"aq_damascus_sg553", "Damascus Steel"},
        {"am_crystallized", "Red Quartz"},
        {"am_crystallized_blue", "Cobalt Quartz"},
        {"hy_varicamo_red", "Full Stop"},
        {"hy_snakeskin", "Pit Viper"},
        {"am_crystallized_silver", "Silver Quartz"},
        {"aa_fade_grassland", "Acid Fade"},
        {"so_orange_accents", "Nitro"},
        {"cu_m4_asimov", "Asiimov"},
        {"cu_sawedoff_octopump", "The Kraken"},
        {"cu_m4a1-s_elegant", "Guardian"},
        {"cu_p250_refined", "Mehndi"},
        {"cu_awp_cobra", "Redline"},
        {"cu_famas_pulse", "Pulse"},
        {"hy_marina_sunrise", "Marina"},
        {"am_thorny_rose_mp9", "Rose Iron"},
        {"cu_skull_nova", "Rising Skull"},
        {"cu_sandstorm", "Sandstorm"},
        {"hy_kami", "Kami"},
        {"aq_obsidian", "Magma"},
        {"am_turqoise_halftone", "Cobalt Halftone"},
        {"am_diamond_plate", "Tread Plate"},
        {"am_fuschia", "The Fuschia Is Now"},
        {"aq_etched_cz75", "Victoria"},
        {"am_p250_beaded_paint", "Undertow"},
        {"am_fluted_tec9", "Titanium Bit"},
        {"aq_engraved_deagle", "Heirloom"},
        {"am_copper_flecks", "Copper Galaxy"},
        {"hy_poly_camo", "Red FragCam"},
        {"so_panther", "Panther"},
        {"aq_usp_stainless", "Stainless"},
        {"hy_craquelure", "Blue Fissure"},
        {"cu_awp_asimov", "Asiimov"},
        {"cu_aug_chameleonaire", "Chameleon"},
        {"cu_ump_corporal", "Corporal"},
        {"cu_ak47_cobra", "Redline"},
        {"cu_p90_trigon", "Trigon"},
        {"cu_mac10_redhot", "Heat"},
        {"sp_negev_turq_terrain", "Terrain"},
        {"cu_nova_antique", "Antique"},
        {"cu_sg553_pulse", "Pulse"},
        {"an_famas_sgt", "Sergeant"},
        {"cu_tec9_sandstorm", "Sandstorm"},
        {"cu_usp_elegant", "Guardian"},
        {"cu_mag7_heaven", "Heaven Guard"},
        {"hy_nerodia", "Death Rattle"},
        {"so_green", "Green Apple"},
        {"cu_money", "Franklin"},
        {"am_crystallized_dark", "Meteorite"},
        {"so_orca", "Tuxedo"},
        {"am_army_shine", "Army Sheen"},
        {"am_oval_hex", "Caged Steel"},
        {"cu_pinstripe_ak47", "Emerald Pinstripe"},
        {"am_m4a1-s_alloy_orange", "Atomic Alloy"},
        {"cu_ak47_rubber", "Vulcan"},
        {"cu_tec9_asiimov", "Isaac"},
        {"cu_ssg08_immortal", "Slashed"},
        {"cu_aug_progressiv", "Torque"},
        {"cu_bizon_antique", "Antique"},
        {"cu_retribution", "Retribution"},
        {"hy_galil_kami", "Kami"},
        {"cu_m4a1_howling", "Howl"},
        {"cu_mac10_decay", "Curse"},
        {"cu_p90_scorpius", "Desert Warfare"},
        {"cu_scar_cyrex", "Cyrex"},
        {"cu_usp_spitfire", "Orion"},
        {"cu_xm1014_heaven_guard", "Heaven Guard"},
        {"am_nitrogen", "Poison Dart"},
        {"cu_panther_ak47", "Jaguar"},
        {"cu_bratatat_negev", "Bratatat"},
        {"cu_usp_sandpapered", "Road Rash"},
        {"hy_ssg08_marker", "Detour"},
        {"hy_snakeskin_red", "Red Python"},
        {"cu_m4a1-s_silence", "Master Piece"},
        {"so_orange_accents2", "Nitro"},
        {"aq_steel", "Rust Coat"},
        {"am_royal", "Chalice"},
        {"am_metals", "Knight"},
        {"am_chainmail", "Chainmail"},
        {"aq_handcannon", "Hand Cannon"},
        {"am_metal_inlay", "Dark Age"},
        {"hy_vines", "Briar"},
        {"hy_indigo_usp", "Royal Blue"},
        {"so_indigo_and_grey", "Indigo"},
        {"am_gyrate", "Twist"},
        {"an_royalbleed", "Module"},
        {"cu_titanstorm", "Desert-Strike"},
        {"cu_korupt", "Tatter"},
        {"cu_p2000_pulse", "Pulse"},
        {"cu_kaiman", "Caiman"},
        {"cu_well_traveled_ak47", "Jet Set"},
        {"cu_green_leather_ak47", "First Class"},
        {"cu_brown_leather_p90", "Leather"},
        {"cu_luggage_mac10", "Commuter"},
        {"cu_medieval_dragon_awp", "Dragon Lore"},
        {"cu_green_leather_sawedoff", "First Class"},
        {"cu_luggage_p2000", "Coach Class"},
        {"aq_pilot_deagle", "Pilot"},
        {"cu_leather_xm1014", "Red Leather"},
        {"cu_bizon-osiris", "Osiris"},
        {"cu_c75a-tiger", "Tigris"},
        {"cu_deagle_aureus", "Conspiracy"},
        {"aq_57_feathers", "Fowl Play"},
        {"cu_glock-liquescent", "Water Elemental"},
        {"cu_mp7-commander", "Urban Hazard"},
        {"cu_negev_titanstorm", "Desert-Strike"},
        {"cu_nova_koi", "Koi"},
        {"cu_p2000_ivory", "Ivory"},
        {"cu_bittersweet", "Supernova"},
        {"cu_p90-asiimov", "Asiimov"},
        {"cu_m4a1s_cyrex", "Cyrex"},
        {"aq_leviathan", "Abyss"},
        {"hy_lines_orange", "Labyrinth"},
        {"cu_luggage_sg553", "Traveler"},
        {"cu_luggage_usp-s", "Business Class"},
        {"hy_plaid1", "Olive Plaid"},
        {"hy_plaid2", "Green Plaid"},
        {"am_nuclear_pattern1_glock", "Reactor"},
        {"hy_nuclear_pattern2_mp9", "Setting Sun"},
        {"sp_nuclear_pattern3_negev", "Nuclear Waste"},
        {"am_nuclear_skulls1_xm1014", "Bone Machine"},
        {"am_nuclear_skulls2_famas", "Styx"},
        {"am_nuclear_skulls3_mac10", "Nuclear Garden"},
        {"hy_nuclear_skulls4_p250", "Contamination"},
        {"hy_nuclear_skulls5_tec9", "Toxic"},
        {"sp_nukestripe_orange_aug", "Radiation Hazard"},
        {"so_grey_nuclear_green_bizon", "Chemical Green"},
        {"so_grey_nuclear_orange_five_seven", "Hot Shot"},
        {"sp_spray_radiation_hazard", "Radiation Hazard"}
};
PaintKit get_paintkit_by_weapon_type_and_skin(const std::vector<PaintKit>& paintkits, ItemDefinitionIndex weapon_type, const std::string& skin_name) {
    for (size_t i = 0; i < paintkits.size(); i++) {
        if (paintkits[i].weapon_type == weapon_type && paintkits[i].skin_name == skin_name) {
            return paintkits[i];
        }
    }
    return PaintKit(0,"",0);
}
const char* PaintKitToSkinName(PaintKit kit) {
    std::string skin_name_str(kit.skin_name); 
    auto it = paintkitnames.find(skin_name_str); 
    if (it != paintkitnames.end()) {
        return it->second.c_str(); 
    }
    else {
        return "U";
    }
}

std::unordered_map<int, PaintKit> skins;
ItemDefinitionIndex CTKnife = WEAPON_KNIFE_KARAMBIT;
ItemDefinitionIndex TKnife = WEAPON_KNIFE_GUT;